/*--------------------------------------------------------------------------
 * This file is autogenerated from config.h.in 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/

#ifndef _CONFIGURATION_HEADER_GUARD_H_
#define _CONFIGURATION_HEADER_GUARD_H_

#define VERSION_MAJOR 2
#define VERSION_MINOR 4
#define VERSION_PATCH 2
#define VERSION "2.4.2"

#define GOOGLE_TAG  "gifkdhkmnilbgakhgopgeaicgmfbkcha"
#define MOZILLA_TAG "zeroconf_lookup@railduino.com"

#endif

